[book]
authors = ["Rahul Solanki"]
language = "en"
multilingual = false
src = "src"
title = "French grammer with English"

[output.html]
additional-css = ["./CustomStyles/Custom.css"]

[output.html.fold]
enable = false    # whether or not to enable section folding
level = 0    

[output.html.playground]
editable = false         # allows editing the source code
copyable = false          # include the copy button for copying code snippets
copy-js = false           # includes the JavaScript for the code editor
line-numbers = false     # displays line numbers for editable code
runnable = false 